import { Service } from "@/types/booking";

export const SERVICES: Service[] = [
  {
    id: "oil",
    nameFi: "Öljynvaihto",
    nameEn: "Oil Change",
    descFi: "Moottoriöljyn ja suodattimen vaihto kaikille automerkeille",
    descEn: "Engine oil and filter replacement for all car brands",
    price: 79,
    durationFi: "~30 min",
    durationEn: "~30 min",
    icon: "🛢️",
  },
  {
    id: "brakes",
    nameFi: "Jarruhuolto",
    nameEn: "Brake Service",
    descFi: "Jarrulevyjen ja -palojen tarkistus ja vaihto",
    descEn: "Brake disc and pad inspection and replacement",
    price: 149,
    durationFi: "~2 h",
    durationEn: "~2 h",
    icon: "⚙️",
  },
  {
    id: "timing",
    nameFi: "Jakohihnan vaihto",
    nameEn: "Timing Belt",
    descFi: "Kriittinen moottorin huolto — älä lykkää",
    descEn: "Critical engine maintenance — don't delay",
    price: 499,
    durationFi: "~4-6 h",
    durationEn: "~4-6 h",
    icon: "🔧",
  },
  {
    id: "inspection",
    nameFi: "Katsastushuolto",
    nameEn: "MOT Preparation",
    descFi: "Valmistamme autosi katsastukseen — läpäisytakuu",
    descEn: "We prepare your car for MOT — pass guarantee",
    price: 99,
    durationFi: "~1 h",
    durationEn: "~1 h",
    icon: "✅",
  },
  {
    id: "diag",
    nameFi: "Vikadiagnostiikka",
    nameEn: "Car Diagnostics",
    descFi: "OBD2-vianhaku — moottorivaroitusvalo ja muut viat",
    descEn: "OBD2 fault scan — engine warning light and other faults",
    price: 69,
    durationFi: "~45 min",
    durationEn: "~45 min",
    icon: "📡",
  },
  {
    id: "ac",
    nameFi: "Ilmastointihuolto",
    nameEn: "AC Service",
    descFi: "Ilmastoinnin puhdistus, huolto ja kylmäaineen täyttö",
    descEn: "AC cleaning, service and refrigerant refill",
    price: 89,
    durationFi: "~1 h",
    durationEn: "~1 h",
    icon: "❄️",
  },
];

export const TIME_SLOTS = [
  "08:00","09:00","10:00","11:00","12:00",
  "13:00","14:00","15:00","16:00",
];
